services:
  postgres:
    image: postgres:14
    container_name: graph-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: graph
      POSTGRES_DB: graph
      LANG: C
      LC_ALL: C
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - pgdata:/var/lib/postgresql/data

  ipfs:
    image: ipfs/kubo:v0.27.0
    container_name: graph-ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfsdata:/data/ipfs

  graph-node:
    image: graphprotocol/graph-node:v0.34.0
    container_name: graph-node
    depends_on:
      - postgres
      - ipfs
    ports:
      - "8000:8000"   # GraphQL
      - "8001:8001"   # Admin
      - "8020:8020"   # Index node
    environment:
      postgres_host: postgres
      postgres_user: graph
      postgres_pass: graph
      postgres_db: graph
      ipfs: http://ipfs:5001
      ethereum: hardhat:http://host.docker.internal:8545
      GRAPH_LOG: info
      GRAPH_ETH_CALL_GAS_LIMIT: "50000000"
      
volumes:
  pgdata:
  ipfsdata:
